blank_issues_enabled: false
contact_links:
  - name: ğŸ“š é¡¹ç›®æ–‡æ¡£
    url: https://github.com/Liweimin0512/-GodotPlatform2D/blob/main/readme.md
    about: åœ¨æäº¤ issue ä¹‹å‰ï¼Œè¯·å…ˆæŸ¥çœ‹é¡¹ç›®æ–‡æ¡£
  - name: ğŸ’¬ discordæœåŠ¡å™¨
    url: https://discord.gg/V5nuzC2BcJ
    about: åŠ å…¥discordæœåŠ¡å™¨è·å–å¸®åŠ©å’Œäº¤æµ
  - name: ğŸŒŸ çŸ¥è¯†æ˜Ÿçƒ
    url: https://t.zsxq.com/12B5zOA6n
    about: åŠ å…¥çŸ¥è¯†æ˜Ÿçƒè·å–æ›´å¤šæ”¯æŒ
